// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentsManager.WebApi.Data;

#nullable disable

namespace PaymentsManager.WebApi.Migrations.PaymentsManagerDb
{
    [DbContext(typeof(PaymentsManagerDbContext))]
    [Migration("20231208002514_Creating PaymmentsMManagerDb")]
    partial class CreatingPaymmentsMManagerDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentsManager.WebApi.Models.Domain.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AfpDiscountRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IsssDiscountRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RentDiscountRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("SpreadSheetDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SpreedSheetFileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpreedSheetFileId");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("PaymentsManager.WebApi.Models.Domain.SpreedSheetFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SpreedSheetFiles");
                });

            modelBuilder.Entity("PaymentsManager.WebApi.Models.Domain.PaymentRecord", b =>
                {
                    b.HasOne("PaymentsManager.WebApi.Models.Domain.SpreedSheetFile", null)
                        .WithMany("PaymentRecords")
                        .HasForeignKey("SpreedSheetFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaymentsManager.WebApi.Models.Domain.SpreedSheetFile", b =>
                {
                    b.Navigation("PaymentRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
